[package]
name = "watchman"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
notify = "8.0.0"
render_core = { path = "../render-core" }
serde_json = "1.0.140"
tokio = "1.45.1"
warp = "0.3.7"
wasm-bindgen = "0.2.100"

[lib]
path = "src/lib.rs"
