[package]
name = "render_core"
version = "0.1.0"
edition = "2024"

[dependencies]
designtime_ast = { path = "../ast" }
dominate = { path = "../dominate" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
